title: "Giuliano Tuzzi"
description: "Data Science & Generative AI • Engineering Background"
theme: jekyll-theme-cayman

# Top navbar items
nav:
  - title: "About"
    url: /
  - title: "Projects"
    url: /projects
  - title: "Resume"
    url: /resume
  - title: "Contact"
    url: /contact

# Tell Jekyll about your projects collection
collections:
  projects:
    output: true
    permalink: /projects/:name/

# (Optional) Nice URLs for pages
permalink: pretty
